spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nalda-db.c2k2xt6qu8x0.ap-northeast-2.rds.amazonaws.com:3306/NALDA_db
    username: NALDA_admin
    password: Blueskin741^
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
server:
  tomcat:
    remoteip:
      host-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: "10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|20\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}|0:0:0:0:0:0:0:1|::1"
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-password: ssafy1357
    key-alias: naldakey
    key-store-password: ssafy1357
  http2:
    enabled: true
