spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nalda-db.c2k2xt6qu8x0.ap-northeast-2.rds.amazonaws.com:3306/NALDA_db
    username: NALDA_admin
    password: Blueskin741^
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-password: ssafy1357
#    key-alias: naldakey
#    key-store-password: ssafy1357
#  http2:
#    enabled: true


